CREATE TABLE cbcppurchases (
Cp_id  MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
qedate  DATETIME NOT NULL,
YWWB98D VARCHAR(20) NOT NULL,
YWWB58C VARCHAR(40) NOT NULL,
YWWB99O VARCHAR(60) NOT NULL,
YWWB8X8 VARCHAR(40) NOT NULL,
YWWB37P VARCHAR(40) NOT NULL,
YWWB8X9 VARCHAR(40) NOT NULL,
YWWB97O VARCHAR(40) NOT NULL,
PRIMARY KEY (Cp_id)
);

